[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --skip-update-check --chip esp32s3 --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
]

[unstable]
build-std = ["core"]
